name: Feature/BugFix

on: [ push ]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare
      uses: ./.github/actions/prepare
      with:
        node-version: ${{ matrix.node-version }}
        
  lint:
    needs: cache-and-install

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        run: pnpm lint

  e2e-tests:
    needs: cache-and-install

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: pnpm --dir apps/e2e/ cypress:run
          start: pnpm --dir apps/web/ dev
          wait-on: 'http://localhost:3000'

  e2e-tests-docker:
    needs: cache-and-install

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install global dependencies
        id: global-dependencies
        shell: bash
        run: npm i -g npm-run-all

      - name: Build docker image
        shell: bash
        run: npm run --prefix apps/e2e/ docker:build

      - name: Build testing docker image
        shell: bash
        run: npm run --prefix apps/e2e/ docker:build:e2e

      - name: Run Cypress tests
        shell: bash
        run: npm run --prefix apps/e2e/ docker:test
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: apps/e2e/coverage